package xxatcust.oracle.apps.sudoku.model.module.common;

import java.util.List;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 31 17:44:29 IST 2019
// ---------------------------------------------------------------------
public interface SudokuAM extends ApplicationModule {
    List<String> getNodeCategoryList();
}
