package xxatcust.oracle.apps.sudoku.model.module.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 13 21:53:45 IST 2019
// ---------------------------------------------------------------------
public interface SudokuAM extends ApplicationModule {
   

    void clearQuoteFields();


    void searchQuote();

    void initQuoteSearch();

    void getQuoteCustmerAddress();

    String callQuoteAPI();

    void getUpdateQuote();

    String callUpdateQuoteAPI();

    void initRuleSet();
}
