package xxatcust.oracle.apps.sudoku.model.module.client;

import java.util.List;

import oracle.jbo.client.remote.ApplicationModuleImpl;

import xxatcust.oracle.apps.sudoku.model.module.common.SudokuAM;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 31 17:44:29 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SudokuAMClient extends ApplicationModuleImpl implements SudokuAM {
    /**
     * This is the default constructor (do not remove).
     */
    public SudokuAMClient() {
    }

    public List<String> getNodeCategoryList() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getNodeCategoryList",null,null);
        return (List<String>)_ret;
    }
}
