package xxatcust.oracle.apps.sudoku.model.readonlyvo;

import java.math.BigDecimal;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 25 14:33:35 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class QuotesVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        QuoteDescription {
            public Object get(QuotesVORowImpl obj) {
                return obj.getQuoteDescription();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setQuoteDescription((String)value);
            }
        }
        ,
        DealId {
            public Object get(QuotesVORowImpl obj) {
                return obj.getDealId();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setDealId((String)value);
            }
        }
        ,
        SalesChannel {
            public Object get(QuotesVORowImpl obj) {
                return obj.getSalesChannel();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setSalesChannel((String)value);
            }
        }
        ,
        SalesRepresentative {
            public Object get(QuotesVORowImpl obj) {
                return obj.getSalesRepresentative();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setSalesRepresentative((String)value);
            }
        }
        ,
        CustomerSupportRepresent {
            public Object get(QuotesVORowImpl obj) {
                return obj.getCustomerSupportRepresent();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setCustomerSupportRepresent((String)value);
            }
        }
        ,
        OrganizationUnit {
            public Object get(QuotesVORowImpl obj) {
                return obj.getOrganizationUnit();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setOrganizationUnit((String)value);
            }
        }
        ,
        OrderType {
            public Object get(QuotesVORowImpl obj) {
                return obj.getOrderType();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setOrderType((String)value);
            }
        }
        ,
        CustomerName {
            public Object get(QuotesVORowImpl obj) {
                return obj.getCustomerName();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setCustomerName((String)value);
            }
        }
        ,
        CustomerNumber {
            public Object get(QuotesVORowImpl obj) {
                return obj.getCustomerNumber();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setCustomerNumber((String)value);
            }
        }
        ,
        AdvantestQuotationNumber {
            public Object get(QuotesVORowImpl obj) {
                return obj.getAdvantestQuotationNumber();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setAdvantestQuotationNumber((String)value);
            }
        }
        ,
        QuotationDate {
            public Object get(QuotesVORowImpl obj) {
                return obj.getQuotationDate();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setQuotationDate((String)value);
            }
        }
        ,
        Page {
            public Object get(QuotesVORowImpl obj) {
                return obj.getPage();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setPage((String)value);
            }
        }
        ,
        Systemid {
            public Object get(QuotesVORowImpl obj) {
                return obj.getSystemid();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setSystemid((String)value);
            }
        }
        ,
        PaymentTerms {
            public Object get(QuotesVORowImpl obj) {
                return obj.getPaymentTerms();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setPaymentTerms((String)value);
            }
        }
        ,
        IncoTerms {
            public Object get(QuotesVORowImpl obj) {
                return obj.getIncoTerms();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setIncoTerms((String)value);
            }
        }
        ,
        Currency {
            public Object get(QuotesVORowImpl obj) {
                return obj.getCurrency();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setCurrency((String)value);
            }
        }
        ,
        QuoteTo {
            public Object get(QuotesVORowImpl obj) {
                return obj.getQuoteTo();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setQuoteTo((String)value);
            }
        }
        ,
        ShipTo {
            public Object get(QuotesVORowImpl obj) {
                return obj.getShipTo();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setShipTo((String)value);
            }
        }
        ,
        PartyId {
            public Object get(QuotesVORowImpl obj) {
                return obj.getPartyId();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setPartyId((BigDecimal)value);
            }
        }
        ,
        SalesContactName {
            public Object get(QuotesVORowImpl obj) {
                return obj.getSalesContactName();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setSalesContactName((String)value);
            }
        }
        ,
        SalesPhoneNum {
            public Object get(QuotesVORowImpl obj) {
                return obj.getSalesPhoneNum();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setSalesPhoneNum((String)value);
            }
        }
        ,
        SalesFaxNum {
            public Object get(QuotesVORowImpl obj) {
                return obj.getSalesFaxNum();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setSalesFaxNum((String)value);
            }
        }
        ,
        SalesEmail {
            public Object get(QuotesVORowImpl obj) {
                return obj.getSalesEmail();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setSalesEmail((String)value);
            }
        }
        ,
        CustomerContactName {
            public Object get(QuotesVORowImpl obj) {
                return obj.getCustomerContactName();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setCustomerContactName((String)value);
            }
        }
        ,
        CustomerPhoneNum {
            public Object get(QuotesVORowImpl obj) {
                return obj.getCustomerPhoneNum();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setCustomerPhoneNum((String)value);
            }
        }
        ,
        CustomerFaxNum {
            public Object get(QuotesVORowImpl obj) {
                return obj.getCustomerFaxNum();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setCustomerFaxNum((String)value);
            }
        }
        ,
        CustomerEmail {
            public Object get(QuotesVORowImpl obj) {
                return obj.getCustomerEmail();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setCustomerEmail((String)value);
            }
        }
        ,
        Customerparentid {
            public Object get(QuotesVORowImpl obj) {
                return obj.getCustomerparentid();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setCustomerparentid((BigDecimal)value);
            }
        }
        ,
        AttentionToOrDept {
            public Object get(QuotesVORowImpl obj) {
                return obj.getAttentionToOrDept();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setAttentionToOrDept((String)value);
            }
        }
        ,
        QuoteEmail {
            public Object get(QuotesVORowImpl obj) {
                return obj.getQuoteEmail();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setQuoteEmail((String)value);
            }
        }
        ,
        OrgId {
            public Object get(QuotesVORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setOrgId((BigDecimal)value);
            }
        }
        ,
        PriceList {
            public Object get(QuotesVORowImpl obj) {
                return obj.getPriceList();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setPriceList((String)value);
            }
        }
        ,
        CustAccid {
            public Object get(QuotesVORowImpl obj) {
                return obj.getCustAccid();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setCustAccid((String)value);
            }
        }
        ,
        BusinessAgreement {
            public Object get(QuotesVORowImpl obj) {
                return obj.getBusinessAgreement();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setBusinessAgreement((String)value);
            }
        }
        ,
        BusinessAgreementId {
            public Object get(QuotesVORowImpl obj) {
                return obj.getBusinessAgreementId();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setBusinessAgreementId((String)value);
            }
        }
        ,
        Discount {
            public Object get(QuotesVORowImpl obj) {
                return obj.getDiscount();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setDiscount((String)value);
            }
        }
        ,
        SalesRepName {
            public Object get(QuotesVORowImpl obj) {
                return obj.getSalesRepName();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setSalesRepName((String)value);
            }
        }
        ,
        OUVO {
            public Object get(QuotesVORowImpl obj) {
                return obj.getOUVO();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        OrderTypeVO {
            public Object get(QuotesVORowImpl obj) {
                return obj.getOrderTypeVO();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CustomerNameVO {
            public Object get(QuotesVORowImpl obj) {
                return obj.getCustomerNameVO();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SalesChannelVO {
            public Object get(QuotesVORowImpl obj) {
                return obj.getSalesChannelVO();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SalesRepresentativeVO {
            public Object get(QuotesVORowImpl obj) {
                return obj.getSalesRepresentativeVO();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CustomerNumberVO {
            public Object get(QuotesVORowImpl obj) {
                return obj.getCustomerNumberVO();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CustomerSupportRepresentVO {
            public Object get(QuotesVORowImpl obj) {
                return obj.getCustomerSupportRepresentVO();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IncoTermVO1 {
            public Object get(QuotesVORowImpl obj) {
                return obj.getIncoTermVO1();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        NodeCategoryVO {
            public Object get(QuotesVORowImpl obj) {
                return obj.getNodeCategoryVO();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PaymentTermsVO {
            public Object get(QuotesVORowImpl obj) {
                return obj.getPaymentTermsVO();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PrimarySalesPersonVO {
            public Object get(QuotesVORowImpl obj) {
                return obj.getPrimarySalesPersonVO();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        QuotesVO {
            public Object get(QuotesVORowImpl obj) {
                return obj.getQuotesVO();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CurrencyVO {
            public Object get(QuotesVORowImpl obj) {
                return obj.getCurrencyVO();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PriceListVO {
            public Object get(QuotesVORowImpl obj) {
                return obj.getPriceListVO();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        businessAgreementVo {
            public Object get(QuotesVORowImpl obj) {
                return obj.getbusinessAgreementVo();
            }

            public void put(QuotesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(QuotesVORowImpl object);

        public abstract void put(QuotesVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int QUOTEDESCRIPTION = AttributesEnum.QuoteDescription.index();
    public static final int DEALID = AttributesEnum.DealId.index();
    public static final int SALESCHANNEL = AttributesEnum.SalesChannel.index();
    public static final int SALESREPRESENTATIVE = AttributesEnum.SalesRepresentative.index();
    public static final int CUSTOMERSUPPORTREPRESENT = AttributesEnum.CustomerSupportRepresent.index();
    public static final int ORGANIZATIONUNIT = AttributesEnum.OrganizationUnit.index();
    public static final int ORDERTYPE = AttributesEnum.OrderType.index();
    public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
    public static final int CUSTOMERNUMBER = AttributesEnum.CustomerNumber.index();
    public static final int ADVANTESTQUOTATIONNUMBER = AttributesEnum.AdvantestQuotationNumber.index();
    public static final int QUOTATIONDATE = AttributesEnum.QuotationDate.index();
    public static final int PAGE = AttributesEnum.Page.index();
    public static final int SYSTEMID = AttributesEnum.Systemid.index();
    public static final int PAYMENTTERMS = AttributesEnum.PaymentTerms.index();
    public static final int INCOTERMS = AttributesEnum.IncoTerms.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int QUOTETO = AttributesEnum.QuoteTo.index();
    public static final int SHIPTO = AttributesEnum.ShipTo.index();
    public static final int PARTYID = AttributesEnum.PartyId.index();
    public static final int SALESCONTACTNAME = AttributesEnum.SalesContactName.index();
    public static final int SALESPHONENUM = AttributesEnum.SalesPhoneNum.index();
    public static final int SALESFAXNUM = AttributesEnum.SalesFaxNum.index();
    public static final int SALESEMAIL = AttributesEnum.SalesEmail.index();
    public static final int CUSTOMERCONTACTNAME = AttributesEnum.CustomerContactName.index();
    public static final int CUSTOMERPHONENUM = AttributesEnum.CustomerPhoneNum.index();
    public static final int CUSTOMERFAXNUM = AttributesEnum.CustomerFaxNum.index();
    public static final int CUSTOMEREMAIL = AttributesEnum.CustomerEmail.index();
    public static final int CUSTOMERPARENTID = AttributesEnum.Customerparentid.index();
    public static final int ATTENTIONTOORDEPT = AttributesEnum.AttentionToOrDept.index();
    public static final int QUOTEEMAIL = AttributesEnum.QuoteEmail.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int PRICELIST = AttributesEnum.PriceList.index();
    public static final int CUSTACCID = AttributesEnum.CustAccid.index();
    public static final int BUSINESSAGREEMENT = AttributesEnum.BusinessAgreement.index();
    public static final int BUSINESSAGREEMENTID = AttributesEnum.BusinessAgreementId.index();
    public static final int DISCOUNT = AttributesEnum.Discount.index();
    public static final int SALESREPNAME = AttributesEnum.SalesRepName.index();
    public static final int OUVO = AttributesEnum.OUVO.index();
    public static final int ORDERTYPEVO = AttributesEnum.OrderTypeVO.index();
    public static final int CUSTOMERNAMEVO = AttributesEnum.CustomerNameVO.index();
    public static final int SALESCHANNELVO = AttributesEnum.SalesChannelVO.index();
    public static final int SALESREPRESENTATIVEVO = AttributesEnum.SalesRepresentativeVO.index();
    public static final int CUSTOMERNUMBERVO = AttributesEnum.CustomerNumberVO.index();
    public static final int CUSTOMERSUPPORTREPRESENTVO = AttributesEnum.CustomerSupportRepresentVO.index();
    public static final int INCOTERMVO1 = AttributesEnum.IncoTermVO1.index();
    public static final int NODECATEGORYVO = AttributesEnum.NodeCategoryVO.index();
    public static final int PAYMENTTERMSVO = AttributesEnum.PaymentTermsVO.index();
    public static final int PRIMARYSALESPERSONVO = AttributesEnum.PrimarySalesPersonVO.index();
    public static final int QUOTESVO = AttributesEnum.QuotesVO.index();
    public static final int CURRENCYVO = AttributesEnum.CurrencyVO.index();
    public static final int PRICELISTVO = AttributesEnum.PriceListVO.index();
    public static final int BUSINESSAGREEMENTVO = AttributesEnum.businessAgreementVo.index();

    /**
     * This is the default constructor (do not remove).
     */
    public QuotesVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute QuoteDescription.
     * @return the QuoteDescription
     */
    public String getQuoteDescription() {
        return (String) getAttributeInternal(QUOTEDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute QuoteDescription.
     * @param value value to set the  QuoteDescription
     */
    public void setQuoteDescription(String value) {
        setAttributeInternal(QUOTEDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DealId.
     * @return the DealId
     */
    public String getDealId() {
        return (String) getAttributeInternal(DEALID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DealId.
     * @param value value to set the  DealId
     */
    public void setDealId(String value) {
        setAttributeInternal(DEALID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SalesChannel.
     * @return the SalesChannel
     */
    public String getSalesChannel() {
        return (String) getAttributeInternal(SALESCHANNEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SalesChannel.
     * @param value value to set the  SalesChannel
     */
    public void setSalesChannel(String value) {
        setAttributeInternal(SALESCHANNEL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SalesRepresentative.
     * @return the SalesRepresentative
     */
    public String getSalesRepresentative() {
        return (String) getAttributeInternal(SALESREPRESENTATIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SalesRepresentative.
     * @param value value to set the  SalesRepresentative
     */
    public void setSalesRepresentative(String value) {
        setAttributeInternal(SALESREPRESENTATIVE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerSupportRepresent.
     * @return the CustomerSupportRepresent
     */
    public String getCustomerSupportRepresent() {
        return (String) getAttributeInternal(CUSTOMERSUPPORTREPRESENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerSupportRepresent.
     * @param value value to set the  CustomerSupportRepresent
     */
    public void setCustomerSupportRepresent(String value) {
        setAttributeInternal(CUSTOMERSUPPORTREPRESENT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrganizationUnit.
     * @return the OrganizationUnit
     */
    public String getOrganizationUnit() {
        return (String) getAttributeInternal(ORGANIZATIONUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrganizationUnit.
     * @param value value to set the  OrganizationUnit
     */
    public void setOrganizationUnit(String value) {
        setAttributeInternal(ORGANIZATIONUNIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrderType.
     * @return the OrderType
     */
    public String getOrderType() {
        return (String) getAttributeInternal(ORDERTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrderType.
     * @param value value to set the  OrderType
     */
    public void setOrderType(String value) {
        setAttributeInternal(ORDERTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerName.
     * @return the CustomerName
     */
//    public String getCustomerName() {
//        return (String) getAttributeInternal(CUSTOMERNAME);
//    }
    public String getCustomerName() {
  if (getAttributeInternal(CUSTOMERNUMBER)!=null) {
            String custName = null;
            Object partyId = getAttributeInternal(PARTYID);
            if (partyId != null) {
                System.out.println("partyId:" + partyId);
                if (partyId != null) {
                    Object[] obj = { partyId };
                    Key key = new Key(obj);
                    Row[] rows = this.getCustomerNumberVO().findByKey(key, 1);
                    if (rows != null && rows.length > 0) {
                        custName =
                                (String)rows[0].getAttribute("Customername");
                    }
                    System.out.println("custName from VORowImpl:" + custName);
                }
                
            }
            return custName;
        }
  else
          return (String) getAttributeInternal(CUSTOMERNAME);
}

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerName.
     * @param value value to set the  CustomerName
     */
    public void setCustomerName(String value) {
        setAttributeInternal(CUSTOMERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerNumber.
     * @return the CustomerNumber
     */
//    public String getCustomerNumber() {
//        return (String) getAttributeInternal(CUSTOMERNUMBER);
//    }
    public String getCustomerNumber() {
        
        if (getAttributeInternal(CUSTOMERNAME)!=null) {
            Object partyId = getAttributeInternal(PARTYID);
            String custNum = null;
            if (partyId != null) {
                Object[] obj = { partyId };
                Key key = new Key(obj);
                Row[] rows = this.getCustomerNumberVO().findByKey(key, 1);
                if (rows != null && rows.length > 0) {
                    custNum = (String)rows[0].getAttribute("Accountnumber");
                }

            }
            return custNum;
        }
        else
        return (String) getAttributeInternal(CUSTOMERNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerNumber.
     * @param value value to set the  CustomerNumber
     */
    public void setCustomerNumber(String value) {
        setAttributeInternal(CUSTOMERNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AdvantestQuotationNumber.
     * @return the AdvantestQuotationNumber
     */
    public String getAdvantestQuotationNumber() {
        return (String) getAttributeInternal(ADVANTESTQUOTATIONNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AdvantestQuotationNumber.
     * @param value value to set the  AdvantestQuotationNumber
     */
    public void setAdvantestQuotationNumber(String value) {
        setAttributeInternal(ADVANTESTQUOTATIONNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute QuotationDate.
     * @return the QuotationDate
     */
    public String getQuotationDate() {
        return (String) getAttributeInternal(QUOTATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute QuotationDate.
     * @param value value to set the  QuotationDate
     */
    public void setQuotationDate(String value) {
        setAttributeInternal(QUOTATIONDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Page.
     * @return the Page
     */
    public String getPage() {
        return (String) getAttributeInternal(PAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Page.
     * @param value value to set the  Page
     */
    public void setPage(String value) {
        setAttributeInternal(PAGE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Systemid.
     * @return the Systemid
     */
    public String getSystemid() {
        return (String) getAttributeInternal(SYSTEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Systemid.
     * @param value value to set the  Systemid
     */
    public void setSystemid(String value) {
        setAttributeInternal(SYSTEMID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PaymentTerms.
     * @return the PaymentTerms
     */
    public String getPaymentTerms() {
        return (String) getAttributeInternal(PAYMENTTERMS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PaymentTerms.
     * @param value value to set the  PaymentTerms
     */
    public void setPaymentTerms(String value) {
        setAttributeInternal(PAYMENTTERMS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IncoTerms.
     * @return the IncoTerms
     */
    public String getIncoTerms() {
        return (String) getAttributeInternal(INCOTERMS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IncoTerms.
     * @param value value to set the  IncoTerms
     */
    public void setIncoTerms(String value) {
        setAttributeInternal(INCOTERMS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Currency.
     * @return the Currency
     */
    public String getCurrency() {
        return (String) getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Currency.
     * @param value value to set the  Currency
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute QuoteTo.
     * @return the QuoteTo
     */
    public String getQuoteTo() {
        return (String) getAttributeInternal(QUOTETO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute QuoteTo.
     * @param value value to set the  QuoteTo
     */
    public void setQuoteTo(String value) {
        setAttributeInternal(QUOTETO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ShipTo.
     * @return the ShipTo
     */
    public String getShipTo() {
        return (String) getAttributeInternal(SHIPTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ShipTo.
     * @param value value to set the  ShipTo
     */
    public void setShipTo(String value) {
        setAttributeInternal(SHIPTO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PartyId.
     * @return the PartyId
     */
    public BigDecimal getPartyId() {
        return (BigDecimal)getAttributeInternal(PARTYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PartyId.
     * @param value value to set the  PartyId
     */
    public void setPartyId(BigDecimal value) {
        setAttributeInternal(PARTYID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SalesContactName.
     * @return the SalesContactName
     */
    public String getSalesContactName() {
        return (String) getAttributeInternal(SALESCONTACTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SalesContactName.
     * @param value value to set the  SalesContactName
     */
    public void setSalesContactName(String value) {
        setAttributeInternal(SALESCONTACTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SalesPhoneNum.
     * @return the SalesPhoneNum
     */
    public String getSalesPhoneNum() {
        return (String) getAttributeInternal(SALESPHONENUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SalesPhoneNum.
     * @param value value to set the  SalesPhoneNum
     */
    public void setSalesPhoneNum(String value) {
        setAttributeInternal(SALESPHONENUM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SalesFaxNum.
     * @return the SalesFaxNum
     */
    public String getSalesFaxNum() {
        return (String) getAttributeInternal(SALESFAXNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SalesFaxNum.
     * @param value value to set the  SalesFaxNum
     */
    public void setSalesFaxNum(String value) {
        setAttributeInternal(SALESFAXNUM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SalesEmail.
     * @return the SalesEmail
     */
    public String getSalesEmail() {
        return (String) getAttributeInternal(SALESEMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SalesEmail.
     * @param value value to set the  SalesEmail
     */
    public void setSalesEmail(String value) {
        setAttributeInternal(SALESEMAIL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerContactName.
     * @return the CustomerContactName
     */
    public String getCustomerContactName() {
        return (String) getAttributeInternal(CUSTOMERCONTACTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerContactName.
     * @param value value to set the  CustomerContactName
     */
    public void setCustomerContactName(String value) {
        setAttributeInternal(CUSTOMERCONTACTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerPhoneNum.
     * @return the CustomerPhoneNum
     */
    public String getCustomerPhoneNum() {
        return (String) getAttributeInternal(CUSTOMERPHONENUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerPhoneNum.
     * @param value value to set the  CustomerPhoneNum
     */
    public void setCustomerPhoneNum(String value) {
        setAttributeInternal(CUSTOMERPHONENUM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerFaxNum.
     * @return the CustomerFaxNum
     */
    public String getCustomerFaxNum() {
        return (String) getAttributeInternal(CUSTOMERFAXNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerFaxNum.
     * @param value value to set the  CustomerFaxNum
     */
    public void setCustomerFaxNum(String value) {
        setAttributeInternal(CUSTOMERFAXNUM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerEmail.
     * @return the CustomerEmail
     */
    public String getCustomerEmail() {
        return (String) getAttributeInternal(CUSTOMEREMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerEmail.
     * @param value value to set the  CustomerEmail
     */
    public void setCustomerEmail(String value) {
        setAttributeInternal(CUSTOMEREMAIL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Customerparentid.
     * @return the Customerparentid
     */
    public BigDecimal getCustomerparentid() {
        return (BigDecimal) getAttributeInternal(CUSTOMERPARENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Customerparentid.
     * @param value value to set the  Customerparentid
     */
    public void setCustomerparentid(BigDecimal value) {
        setAttributeInternal(CUSTOMERPARENTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AttentionToOrDept.
     * @return the AttentionToOrDept
     */
    public String getAttentionToOrDept() {
        return (String) getAttributeInternal(ATTENTIONTOORDEPT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AttentionToOrDept.
     * @param value value to set the  AttentionToOrDept
     */
    public void setAttentionToOrDept(String value) {
        setAttributeInternal(ATTENTIONTOORDEPT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute QuoteEmail.
     * @return the QuoteEmail
     */
    public String getQuoteEmail() {
        return (String) getAttributeInternal(QUOTEEMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute QuoteEmail.
     * @param value value to set the  QuoteEmail
     */
    public void setQuoteEmail(String value) {
        setAttributeInternal(QUOTEEMAIL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrgId.
     * @return the OrgId
     */
    public BigDecimal getOrgId() {
        return (BigDecimal) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrgId.
     * @param value value to set the  OrgId
     */
    public void setOrgId(BigDecimal value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PriceList.
     * @return the PriceList
     */
    public String getPriceList() {
        return (String) getAttributeInternal(PRICELIST);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PriceList.
     * @param value value to set the  PriceList
     */
    public void setPriceList(String value) {
        setAttributeInternal(PRICELIST, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustAccid.
     * @return the CustAccid
     */
    public String getCustAccid() {
        return (String) getAttributeInternal(CUSTACCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustAccid.
     * @param value value to set the  CustAccid
     */
    public void setCustAccid(String value) {
        setAttributeInternal(CUSTACCID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BusinessAgreement.
     * @return the BusinessAgreement
     */
    public String getBusinessAgreement() {
        return (String) getAttributeInternal(BUSINESSAGREEMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BusinessAgreement.
     * @param value value to set the  BusinessAgreement
     */
    public void setBusinessAgreement(String value) {
        setAttributeInternal(BUSINESSAGREEMENT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BusinessAgreementId.
     * @return the BusinessAgreementId
     */
    public String getBusinessAgreementId() {
        return (String) getAttributeInternal(BUSINESSAGREEMENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BusinessAgreementId.
     * @param value value to set the  BusinessAgreementId
     */
    public void setBusinessAgreementId(String value) {
        setAttributeInternal(BUSINESSAGREEMENTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Discount.
     * @return the Discount
     */
    public String getDiscount() {
        return (String) getAttributeInternal(DISCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Discount.
     * @param value value to set the  Discount
     */
    public void setDiscount(String value) {
        setAttributeInternal(DISCOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SalesRepName.
     * @return the SalesRepName
     */
    public String getSalesRepName() {
        return (String) getAttributeInternal(SALESREPNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SalesRepName.
     * @param value value to set the  SalesRepName
     */
    public void setSalesRepName(String value) {
        setAttributeInternal(SALESREPNAME, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OUVO.
     */
    public RowSet getOUVO() {
        return (RowSet)getAttributeInternal(OUVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OrderTypeVO.
     */
    public RowSet getOrderTypeVO() {
        return (RowSet)getAttributeInternal(ORDERTYPEVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CustomerNameVO.
     */
    public RowSet getCustomerNameVO() {
        return (RowSet)getAttributeInternal(CUSTOMERNAMEVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SalesChannelVO.
     */
    public RowSet getSalesChannelVO() {
        return (RowSet)getAttributeInternal(SALESCHANNELVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SalesRepresentativeVO.
     */
    public RowSet getSalesRepresentativeVO() {
        return (RowSet)getAttributeInternal(SALESREPRESENTATIVEVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CustomerNumberVO.
     */
    public RowSet getCustomerNumberVO() {
        return (RowSet)getAttributeInternal(CUSTOMERNUMBERVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CustomerSupportRepresentVO.
     */
    public RowSet getCustomerSupportRepresentVO() {
        return (RowSet)getAttributeInternal(CUSTOMERSUPPORTREPRESENTVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> IncoTermVO1.
     */
    public RowSet getIncoTermVO1() {
        return (RowSet)getAttributeInternal(INCOTERMVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> NodeCategoryVO.
     */
    public RowSet getNodeCategoryVO() {
        return (RowSet)getAttributeInternal(NODECATEGORYVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PaymentTermsVO.
     */
    public RowSet getPaymentTermsVO() {
        return (RowSet)getAttributeInternal(PAYMENTTERMSVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PrimarySalesPersonVO.
     */
    public RowSet getPrimarySalesPersonVO() {
        return (RowSet)getAttributeInternal(PRIMARYSALESPERSONVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> QuotesVO.
     */
    public RowSet getQuotesVO() {
        return (RowSet)getAttributeInternal(QUOTESVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CurrencyVO.
     */
    public RowSet getCurrencyVO() {
        return (RowSet)getAttributeInternal(CURRENCYVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PriceListVO.
     */
    public RowSet getPriceListVO() {
        return (RowSet)getAttributeInternal(PRICELISTVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> businessAgreementVo.
     */
    public RowSet getbusinessAgreementVo() {
        return (RowSet)getAttributeInternal(BUSINESSAGREEMENTVO);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
