package xxatcust.oracle.apps.sudoku.model.readonlyvo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 14 20:42:47 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class QuotesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public QuotesVOImpl() {
    }
}
